### ISSUE TITLE
Enforce Settings on Startup - not working

### ISSUE THREAD

**Issue by Inexa5** [Stanzilla/AdvancedInterfaceOptions#13]
Hi, having an issue since patch 8.2 - AIO isn't saving two of my settings even with the Enforce Settings on Startup box checked. The two settings are the Action Cam mode setting and the CVar showQuestTrackingTooltips, which I like to set to 0. Every time I re-log or reload, the Action Cam is reset to off and the CVar is reset to the default value 1. Thanks!

**Comment by Ketho** [comment]
* The Action Cam is a [console command](https://wow.gamepedia.com/CVar_ActionCam), and a special one at that since Blizzard usually shows you a popup every time asking if you want to keep it enabled. Something like [Auto ActionCam](https://www.curseforge.com/wow/addons/aac) would have to be added. I don't know if anything in 8.2 changed in regards to that.

* showQuestTrackingTooltips seems to work fine when I enable/disable it in the CVar Browser. It's also supposed to show you if any addon has last set that cvar.

![image](https://user-images.githubusercontent.com/1073877/61175715-5d541a80-a5b4-11e9-8f40-cc5a263e7f5c.png)

On another note, I tried enabling the **Enforce Settings on Startup** option and set that cvar to "0" but it didn't stop my test addon from setting it to "1" and did not enforce it back to "0"😕

Could you try testing it with all other addons disabled to see if it still resets to default?

**Comment by Inexa5** [comment]
Hi,

I installed Auto Action Cam, thanks for the tip! I also tried disabling all
other add-ons and the issue was resolved that way, thanks
