### ISSUE TITLE
War Within Beta: "Detect World of Warcraft Gaming Mouse" 

### ISSUE THREAD

**Issue by xenophanesnsb** [Stanzilla/AdvancedInterfaceOptions#83]
Stanzilla,

I want to thank you for getting a working version out for the beta so quickly.

I know this isn't your problem, but even with your amazing addon, I'm still unable to get my Steelseries WoW Gaming Mouse to work.

Your addon has the "Detect World of Warcraft Gaming Mouse" option checked.  I also ran the script:

/console enableWowMouse 1 (Enables)

But still no functionality for the mouse buttons that currently work on live.

Again, I know this isn't your problem to fix, but I don't know who else to ask.   Do you have any insight on this?  Did Blizzard break it permanently or is there something I'm missing?  Any guidance would be appreciated.  I will be tipping you for your troubles regardless.

![wowmouseenabled](https://github.com/Stanzilla/AdvancedInterfaceOptions/assets/116731454/4e91f32c-803e-4263-8532-371ae2f08d02)

**Comment by Stanzilla** [comment]
I'll have to take a look but all we do is enable the option in Blizzard's code so if it doesn't work I'd suspect they broke it.

**Comment by xenophanesnsb** [comment]
Any advice would be appreciated.  This is a huge deal for me because I've been frantically looking for mouse options and I don't think I can play WoW without this mouse.  It's been a big hobby of mine since 2005 so this is a big deal for me.  Thanks again for all you do!

**Comment by Warz78** [comment]
> Any advice would be appreciated. This is a huge deal for me because I've been frantically looking for mouse options and I don't think I can play WoW without this mouse. It's been a big hobby of mine since 2005 so this is a big deal for me. Thanks again for all you do!

I think we just need to keep messaging everyone we can at Blizzard and commenting on forum threads trying to bring this to their attention. There is nothing Stanzilla can do because they are simply using the console command that for whatever reason after over a decade Blizzard has either accidently or intentionally disabled.

**Comment by Stanzilla** [comment]
I think this is related and affects mac and Windows https://us.forums.blizzard.com/en/wow/t/mac-os-shift-keybinds-not-working/1900210/32

**Comment by romracer** [comment]
Might be fixed with the browser.lua changes in #90

**Comment by Warz78** [comment]
They just posted on the forums that the mac fix isn't going to fix the WoW Mouse and that they are starting to look into that today. <3

"It’s not related and the fix for the other MMO mice in this thread is not going to fix the old steelseries WoW mice. I’m just starting to look into that issue today."

https://us.forums.blizzard.com/en/wow/t/mac-os-shift-keybinds-not-working/1900210/58

**Comment by Warz78** [comment]
Looks like a patch went live today that fixed most mouse issues but not the issue for the support of the WoW Steelseries Cata mouse. Not sure when that will be live but running out of time to enjoy the prepatch and kind of sad.

**Comment by Warz78** [comment]
Good neeeeeeeeeeeeeeeews everyone. The SteelSeries Cataclysm Mouse is working again. Big thanks to Rommax at Blizzard.

**Comment by brittyazel** [comment]
@Stanzilla Seems resolved, we should close this issue.
